# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Articles | Riotz.works
subtitle:
description: Fun and joy engineering activities articles by members of Riotz.works.
author: Riotz.works
language: ja
timezone: Asia/Tokyo

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://riotz.works/articles
root: /articles/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: dist
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
### hexo-generator-feed (https://github.com/hexojs/hexo-generator-feed)
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub: http://pubsubhubbub.appspot.com

### hexo-generator-sitemap (https://github.com/hexojs/hexo-generator-sitemap)
sitemap:
  path: sitemap.xml

## hexo-html-minifier (https://github.com/hexojs/hexo-html-minifier)
html_minifier:
  collapseBooleanAttributes: true
  collapseInlineTagWhitespace: true
  collapseWhitespace: true
  decodeEntities: true
  minifyCSS: true
  minifyJS: true
  removeComments: true
  removeEmptyAttributes: true
  removeEmptyElements: false  # Note: When this setting is enabled, the header image will not be displayed
  removeOptionalTags: true
  removeRedundantAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  useShortDoctype: true

## hexo-related-popular-posts (https://github.com/tea3/hexo-related-popular-posts)
popularPosts:
  morphologicalAnalysis:
  googleAnalyticsAPI:
    rankingSheet: rankingSheet.txt
    pvMeasurementsStartDate: 2017-11-01
  cache:
    path: hexo-popular-related-posts-cached.json

### Disqus (https://disqus.com/)
disqus_shortname:

## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:riotz-works/articles.git
  branch: master
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }} [ci skip]"

# Authors
authors:
  lulzneko:
    name: lulzneko
    github: lulzneko
    twitter: lulzneko
  lopburny:
    name: lopburny
    github: lopburny
    twitter: lopburny
