version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: ~/workspace
  persist:
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*

jobs:
  setup:
    executor:
      name: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  build:
    executor:
      name: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
      - store_artifacts:
          path: dist
      - persist
  deploy:
    executor:
      name: default
    steps:
      - attach
      - add_ssh_keys:
          fingerprints:
            - "8a:33:c6:ef:c2:7c:b2:e7:8d:4a:2f:90:6d:89:e0:b1"
      - deploy:
          name: Deploy
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "CircleCI"
            git config --global user.email "contact@riotz.works"
            yarn deploy


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - build:
          context: website-articles
          requires:
            - setup
      - deploy:
          context: website-articles
          requires:
            - build
          filters:
            branches:
              only: source
