version: 2
jobs:
  build:
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: ~/workspace
    docker:
      - image: node:8
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: yarn setup
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Validate
          command: yarn validate
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: target/site
  deploy:
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: ~/workspace
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - deploy:
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "contact@riotz.works"
            yarn deploy
      - store_artifacts:
          path: target/site

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: website-articles
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
          context: website-articles
